// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SubscriptionTier string

const (
	SubscriptionTierFree    SubscriptionTier = "free"
	SubscriptionTierPremium SubscriptionTier = "premium"
)

func (e *SubscriptionTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionTier(s)
	case string:
		*e = SubscriptionTier(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionTier: %T", src)
	}
	return nil
}

type NullSubscriptionTier struct {
	SubscriptionTier SubscriptionTier `json:"subscription_tier"`
	Valid            bool             `json:"valid"` // Valid is true if SubscriptionTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionTier) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionTier), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type User struct {
	ID                     int64              `json:"id"`
	FirstName              string             `json:"first_name"`
	LastName               string             `json:"last_name"`
	Email                  string             `json:"email"`
	PasswordHash           string             `json:"password_hash"`
	Role                   UserRole           `json:"role"`
	Tier                   SubscriptionTier   `json:"tier"`
	PasswordResetToken     pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}
