// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, email, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, first_name, last_name, email, password_hash, role, tier, password_reset_token, password_reset_expires_at, created_at, updated_at
`

type CreateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Tier,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password_hash, role, tier, password_reset_token, password_reset_expires_at, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Tier,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, password_hash, role, tier, password_reset_token, password_reset_expires_at, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Tier,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPasswordResetToken = `-- name: GetUserByPasswordResetToken :one
SELECT id, first_name, last_name, email, password_hash, role, tier, password_reset_token, password_reset_expires_at, created_at, updated_at FROM users
WHERE password_reset_token = $1
  AND password_reset_expires_at > NOW()
`

func (q *Queries) GetUserByPasswordResetToken(ctx context.Context, passwordResetToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPasswordResetToken, passwordResetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Tier,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetPassword = `-- name: ResetPassword :one
UPDATE users
SET password_hash             = $1,
    password_reset_token      = NULL,
    password_reset_expires_at = NULL
WHERE id = $2
RETURNING id, first_name, last_name, email, password_hash, role, tier, password_reset_token, password_reset_expires_at, created_at, updated_at
`

type ResetPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, resetPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Tier,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :one
UPDATE users
SET password_reset_token      = $1,
    password_reset_expires_at = $2
WHERE email = $3
RETURNING id, first_name, last_name, email, password_hash, role, tier, password_reset_token, password_reset_expires_at, created_at, updated_at
`

type SetPasswordResetTokenParams struct {
	PasswordResetToken     pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpiresAt pgtype.Timestamptz `json:"password_reset_expires_at"`
	Email                  string             `json:"email"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, setPasswordResetToken, arg.PasswordResetToken, arg.PasswordResetExpiresAt, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Tier,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET password_hash = $1
WHERE id = $2
RETURNING id, first_name, last_name, email, password_hash, role, tier, password_reset_token, password_reset_expires_at, created_at, updated_at
`

type UpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Tier,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTier = `-- name: UpdateTier :one
UPDATE users
SET tier = $1
WHERE id = $2
RETURNING id, first_name, last_name, email, password_hash, role, tier, password_reset_token, password_reset_expires_at, created_at, updated_at
`

type UpdateTierParams struct {
	Tier SubscriptionTier `json:"tier"`
	ID   int64            `json:"id"`
}

func (q *Queries) UpdateTier(ctx context.Context, arg UpdateTierParams) (User, error) {
	row := q.db.QueryRow(ctx, updateTier, arg.Tier, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Tier,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
